version: "3"
networks:
  discoveryserver: 
services:
  discoveryserver:
    build: ./discoveryserver
    image: sdkanse/discoveryserver:0.0.1-SNAPSHOT.jar
    container_name: server
    ports:
      - "8000:8000"
    networks:
      - discoveryserver
   

  hrd_emp_be:
    build: ./hrd_emp_be
    image: sdkanse/hrd_emp_be:0.0.1-SNAPSHOT.jar
    container_name: be
    ports:
      - "8083:8083"
    networks:
      - discoveryserver
    depends_on:
      - discoveryserver
 

  hrd_emp_fe:
    build: ./hrd_emp_fe
    image: sdkanse/hrd_emp_fe:0.0.1-SNAPSHOT.jar
    container_name: fe
    ports:
      - "8082:8082"
    networks:
      - discoveryserver
    depends_on:
      - hrd_emp_be
      - discoveryserver
 

